# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
reviews:
  profile: assertive
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches:
      - main
      - "feat/.*"
      - "epic/.*"
      - "release/.*"
chat:
  auto_reply: true
