// Image manifest - maps winners to their optimized image paths
// Generated by scripts/process-images.js

export const IMAGE_MANIFEST: Record<
  number,
  {
    portrait: { jpg: string; webp: string };
    thumb: { jpg: string; webp: string };
    web: { jpg: string; webp: string };
  }
> = {
  2025: {
    portrait: {
      jpg: "/images/optimized/2025-elian-oliva-portrait.jpg",
      webp: "/images/optimized/2025-elian-oliva-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2025-elian-oliva-thumb.jpg",
      webp: "/images/optimized/2025-elian-oliva-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2025-elian-oliva-web.jpg",
      webp: "/images/optimized/2025-elian-oliva-web.webp",
    },
  },
  2024: {
    portrait: {
      jpg: "/images/optimized/2024-marcus-mozer-portrait.jpg",
      webp: "/images/optimized/2024-marcus-mozer-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2024-marcus-mozer-thumb.jpg",
      webp: "/images/optimized/2024-marcus-mozer-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2024-marcus-mozer-web.jpg",
      webp: "/images/optimized/2024-marcus-mozer-web.webp",
    },
  },
  2023: {
    portrait: {
      jpg: "/images/optimized/2023-josh-snyder-portrait.jpg",
      webp: "/images/optimized/2023-josh-snyder-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2023-josh-snyder-thumb.jpg",
      webp: "/images/optimized/2023-josh-snyder-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2023-josh-snyder-web.jpg",
      webp: "/images/optimized/2023-josh-snyder-web.webp",
    },
  },
  2022: {
    portrait: {
      jpg: "/images/optimized/2022-brayden-dorman-portrait.jpg",
      webp: "/images/optimized/2022-brayden-dorman-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2022-brayden-dorman-thumb.jpg",
      webp: "/images/optimized/2022-brayden-dorman-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2022-brayden-dorman-web.jpg",
      webp: "/images/optimized/2022-brayden-dorman-web.webp",
    },
  },
  2021: {
    portrait: {
      jpg: "/images/optimized/2021-gavin-sawchuk-portrait.jpg",
      webp: "/images/optimized/2021-gavin-sawchuk-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2021-gavin-sawchuk-thumb.jpg",
      webp: "/images/optimized/2021-gavin-sawchuk-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2021-gavin-sawchuk-web.jpg",
      webp: "/images/optimized/2021-gavin-sawchuk-web.webp",
    },
  },
  2020: {
    portrait: {
      jpg: "/images/optimized/2020-q-jones-jr-portrait.jpg",
      webp: "/images/optimized/2020-q-jones-jr-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2020-q-jones-jr-thumb.jpg",
      webp: "/images/optimized/2020-q-jones-jr-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2020-q-jones-jr-web.jpg",
      webp: "/images/optimized/2020-q-jones-jr-web.webp",
    },
  },
  2019: {
    portrait: {
      jpg: "/images/optimized/2019-andrew-gentry-portrait.jpg",
      webp: "/images/optimized/2019-andrew-gentry-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2019-andrew-gentry-thumb.jpg",
      webp: "/images/optimized/2019-andrew-gentry-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2019-andrew-gentry-web.jpg",
      webp: "/images/optimized/2019-andrew-gentry-web.webp",
    },
  },
  2018: {
    portrait: {
      jpg: "/images/optimized/2018-barrett-miller-portrait.jpg",
      webp: "/images/optimized/2018-barrett-miller-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2018-barrett-miller-thumb.jpg",
      webp: "/images/optimized/2018-barrett-miller-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2018-barrett-miller-web.jpg",
      webp: "/images/optimized/2018-barrett-miller-web.webp",
    },
  },
  2017: {
    portrait: {
      jpg: "/images/optimized/2017-max-borghi-portrait.jpg",
      webp: "/images/optimized/2017-max-borghi-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2017-max-borghi-thumb.jpg",
      webp: "/images/optimized/2017-max-borghi-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2017-max-borghi-web.jpg",
      webp: "/images/optimized/2017-max-borghi-web.webp",
    },
  },
  2016: {
    portrait: {
      jpg: "/images/optimized/2016-dylan-mccaffrey-portrait.jpg",
      webp: "/images/optimized/2016-dylan-mccaffrey-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2016-dylan-mccaffrey-thumb.jpg",
      webp: "/images/optimized/2016-dylan-mccaffrey-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2016-dylan-mccaffrey-web.jpg",
      webp: "/images/optimized/2016-dylan-mccaffrey-web.webp",
    },
  },
  2015: {
    portrait: {
      jpg: "/images/optimized/2015-carlo-kemp-portrait.jpg",
      webp: "/images/optimized/2015-carlo-kemp-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2015-carlo-kemp-thumb.jpg",
      webp: "/images/optimized/2015-carlo-kemp-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2015-carlo-kemp-web.jpg",
      webp: "/images/optimized/2015-carlo-kemp-web.webp",
    },
  },
  2014: {
    portrait: {
      jpg: "/images/optimized/2014-mike-morean-portrait.jpg",
      webp: "/images/optimized/2014-mike-morean-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2014-mike-morean-thumb.jpg",
      webp: "/images/optimized/2014-mike-morean-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2014-mike-morean-web.jpg",
      webp: "/images/optimized/2014-mike-morean-web.webp",
    },
  },
  2013: {
    portrait: {
      jpg: "/images/optimized/2013-christian-mccaffrey-portrait.jpg",
      webp: "/images/optimized/2013-christian-mccaffrey-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2013-christian-mccaffrey-thumb.jpg",
      webp: "/images/optimized/2013-christian-mccaffrey-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2013-christian-mccaffrey-web.jpg",
      webp: "/images/optimized/2013-christian-mccaffrey-web.webp",
    },
  },
  2012: {
    portrait: {
      jpg: "/images/optimized/2012-xavier-lewis-portrait.jpg",
      webp: "/images/optimized/2012-xavier-lewis-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2012-xavier-lewis-thumb.jpg",
      webp: "/images/optimized/2012-xavier-lewis-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2012-xavier-lewis-web.jpg",
      webp: "/images/optimized/2012-xavier-lewis-web.webp",
    },
  },
  2011: {
    portrait: {
      jpg: "/images/optimized/2011-sean-rubalcaba-portrait.jpg",
      webp: "/images/optimized/2011-sean-rubalcaba-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2011-sean-rubalcaba-thumb.jpg",
      webp: "/images/optimized/2011-sean-rubalcaba-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2011-sean-rubalcaba-web.jpg",
      webp: "/images/optimized/2011-sean-rubalcaba-web.webp",
    },
  },
  2009: {
    portrait: {
      jpg: "/images/optimized/2009-matt-brown-portrait.jpg",
      webp: "/images/optimized/2009-matt-brown-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2009-matt-brown-thumb.jpg",
      webp: "/images/optimized/2009-matt-brown-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2009-matt-brown-web.jpg",
      webp: "/images/optimized/2009-matt-brown-web.webp",
    },
  },
  2008: {
    portrait: {
      jpg: "/images/optimized/2008-bryan-peters-portrait.jpg",
      webp: "/images/optimized/2008-bryan-peters-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2008-bryan-peters-thumb.jpg",
      webp: "/images/optimized/2008-bryan-peters-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2008-bryan-peters-web.jpg",
      webp: "/images/optimized/2008-bryan-peters-web.webp",
    },
  },
  2007: {
    portrait: {
      jpg: "/images/optimized/2007-tyler-jackson-portrait.jpg",
      webp: "/images/optimized/2007-tyler-jackson-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/2007-tyler-jackson-thumb.jpg",
      webp: "/images/optimized/2007-tyler-jackson-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/2007-tyler-jackson-web.jpg",
      webp: "/images/optimized/2007-tyler-jackson-web.webp",
    },
  },
  1999: {
    portrait: {
      jpg: "/images/optimized/1999-marcus-houston-portrait.jpg",
      webp: "/images/optimized/1999-marcus-houston-portrait.webp",
    },
    thumb: {
      jpg: "/images/optimized/1999-marcus-houston-thumb.jpg",
      webp: "/images/optimized/1999-marcus-houston-thumb.webp",
    },
    web: {
      jpg: "/images/optimized/1999-marcus-houston-web.jpg",
      webp: "/images/optimized/1999-marcus-houston-web.webp",
    },
  },
};

export function getWinnerImage(
  year: number,
  type: "portrait" | "thumb" | "web" = "portrait"
) {
  return IMAGE_MANIFEST[year]?.[type];
}
